name: Daily End to End Test

on:
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch:
jobs:
  sync:
    name: Run End to End test for pulsar
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - develop
          - release-sn-1.14
          - release-sn-1.15
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Set up Maven
        uses: apache/pulsar-test-infra/setup-maven@master
        with:
          maven-version: 3.6.2
      - name: Run e2e Test
        run: |
          mvn clean install -DskipTests
          mvn -pl 'flink-end-to-end-tests/flink-end-to-end-tests-pulsar' test
