name: Run Test for Pull Request

on:
  pull_request:
    branches: [ develop, release-sn-** ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Maven
        uses: apache/pulsar-test-infra/setup-maven@master
        with:
          maven-version: 3.6.2
      - name: Run Unit Test and Install
        run: |
          mvn -ntp -pl 'flink-connectors/flink-connector-pulsar,flink-connectors/flink-sql-connector-pulsar' \
          clean install

